## Clase 1

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

Se utiliza la palabraa DF para definir la funcion que leera toda la dataset en la nomblegatura.

In [2]:
df = pd.read_csv('diabetes_risk_prediction_dataset.csv')

Usamos la funcion .head para saber todos los cabezales de la base de datos.

In [3]:
df.head()

   Patient_ID   Age  ... Doctor_Consultation_Needed Diabetes_Risk
0           1  32.0  ...                        Yes      Moderate
1           2  42.0  ...                        Yes          High
2           3  89.0  ...                        Yes          High
3           4  87.0  ...                        Yes          High
4           5  27.0  ...                        Yes          High

[5 rows x 41 columns]

shape nos da el total de registros y la cantidad de columnas que tenemos.

In [4]:
df.shape

(50000, 41)

El .info() nos da todos los datos de nuestros atributos.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 41 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient_ID                  50000 non-null  int64
 1   Age                         49503 non-null  float64
 2   Gender                      50000 non-null  str
 3   Country                     50000 non-null  str
 4   Height_cm                   47055 non-null  float64
 5   Weight_kg                   47038 non-null  float64
 6   BMI                         50000 non-null  float64
 7   Waist_Circumference_cm      50000 non-null  float64
 8   Blood_Glucose               49041 non-null  float64
 9   HbA1c                       48026 non-null  float64
 10  Fasting_Blood_Sugar         50000 non-null  float64
 11  Insulin_Level               50000 non-null  float64
 12  Blood_Pressure_Systolic     50000 non-null  int64
 13  Blood_Pressure_Diastolic    50000 non-null  int64
 14  Total_Cholesterol           49000 non-null  float64
 15  HDL                         49000 non-null  float64
 16  LDL                         49000 non-null  float64
 17  Triglycerides               49000 non-null  float64
 18  Heart_Rate                  50000 non-null  int64
 19  Physical_Activity_Level     49500 non-null  str
 20  Exercise_Hours_Per_Week     48008 non-null  float64
 21  Daily_Walking_Minutes       48036 non-null  float64
 22  Diet_Quality                50000 non-null  str
 23  Sugar_Intake_Level          50000 non-null  str
 24  Sleep_Hours                 47983 non-null  float64
 25  Stress_Level                50000 non-null  str
 26  Smoking_Status              50000 non-null  str
 27  Alcohol_Consumption         50000 non-null  str
 28  Family_History_Diabetes     50000 non-null  str
 29  Hypertension                50000 non-null  str
 30  Heart_Disease               50000 non-null  str
 31  Fatty_Liver                 50000 non-null  str
 32  PCOS                        50000 non-null  str
 33  Medication_Adherence        49000 non-null  str
 34  Work_Type                   50000 non-null  str
 35  Residence_Type              50000 non-null  str
 36  Daily_Water_Intake_L        50000 non-null  float64
 37  Diabetes_Risk_Score         50000 non-null  int64
 38  AI_Health_Recommendation    50000 non-null  str
 39  Doctor_Consultation_Needed  50000 non-null  str
 40  Diabetes_Risk               50000 non-null  str
dtypes: float64(17), int64(5), str(19)
memory usage: 15.6 MB

.describe() nos da la descripcion total de todos los campos necesarios que tenemos en nuestra dataset.

In [6]:
df.describe()

         Patient_ID           Age  ...  Daily_Water_Intake_L  Diabetes_Risk_Score
count  50000.000000  49503.000000  ...          50000.000000         50000.000000
mean   25000.500000     53.871099  ...              2.998842            74.043920
std    14433.901067     21.130148  ...              1.152273            15.598327
min        1.000000     18.000000  ...              1.000000            13.000000
25%    12500.750000     35.000000  ...              2.000000            64.000000
50%    25000.500000     54.000000  ...              3.000000            75.000000
75%    37500.250000     72.000000  ...              4.000000            86.000000
max    50000.000000     90.000000  ...              5.000000           100.000000

[8 rows x 22 columns]