In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('synthetic_coffee_health_10000.csv')

print('Dataset cargado correctamente')

Dataset cargado correctamente

In [4]:
df.head()

,ID,Age,Gender,Country,Coffee_Intake,Caffeine_mg,Sleep_Hours,Sleep_Quality,BMI,Heart_Rate,Stress_Level,Physical_Activity_Hours,Health_Issues,Occupation,Smoking,Alcohol_Consumption
0,1,40,Male,Germany,3.5,328.1,7.5,Good,24.9,78,Low,14.5,NaN,Other,0,0
1,2,33,Male,Germany,1.0,94.1,6.2,Good,20.0,67,Low,11.0,NaN,Service,0,0
2,3,42,Male,Brazil,5.3,503.7,5.9,Fair,22.7,59,Medium,11.2,Mild,Office,0,0
3,4,53,Male,Germany,2.6,249.2,7.3,Good,24.7,71,Low,6.6,Mild,Other,0,0
4,5,32,Female,Spain,3.1,298.0,5.3,Fair,24.1,76,Medium,8.5,Mild,Student,0,1

In [5]:
df.tail()

,ID,Age,Gender,Country,Coffee_Intake,Caffeine_mg,Sleep_Hours,Sleep_Quality,BMI,Heart_Rate,Stress_Level,Physical_Activity_Hours,Health_Issues,Occupation,Smoking,Alcohol_Consumption
9995,9996,50,Female,Japan,2.1,199.8,6.0,Fair,30.5,50,Medium,10.1,Moderate,Healthcare,0,1
9996,9997,18,Female,UK,3.4,319.2,5.8,Fair,19.1,71,Medium,11.6,Mild,Service,0,0
9997,9998,26,Male,China,1.6,153.4,7.1,Good,25.1,66,Low,13.7,NaN,Student,1,1
9998,9999,40,Female,Finland,3.4,327.1,7.0,Good,19.3,80,Low,0.1,NaN,Student,0,0
9999,10000,42,Female,Brazil,2.9,277.5,6.4,Good,28.1,72,Low,9.8,NaN,Student,1,0

In [6]:
print('Filas: ', df.shape[0])
print('Columnas: ', df.shape[1])

Filas:  10000
Columnas:  16

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       10000 non-null  int64
 1   Age                      10000 non-null  int64
 2   Gender                   10000 non-null  str
 3   Country                  10000 non-null  str
 4   Coffee_Intake            10000 non-null  float64
 5   Caffeine_mg              10000 non-null  float64
 6   Sleep_Hours              10000 non-null  float64
 7   Sleep_Quality            10000 non-null  str
 8   BMI                      10000 non-null  float64
 9   Heart_Rate               10000 non-null  int64
 10  Stress_Level             10000 non-null  str
 11  Physical_Activity_Hours  10000 non-null  float64
 12  Health_Issues            4059 non-null   str
 13  Occupation               10000 non-null  str
 14  Smoking                  10000 non-null  int64
 15  Alcohol_Consumption      10000 non-null  int64
dtypes: float64(5), int64(5), str(6)
memory usage: 1.2 MB

In [8]:
df.dtypes

ID                           int64
Age                          int64
Gender                         str
Country                        str
Coffee_Intake              float64
Caffeine_mg                float64
Sleep_Hours                float64
Sleep_Quality                  str
BMI                        float64
Heart_Rate                   int64
Stress_Level                   str
Physical_Activity_Hours    float64
Health_Issues                  str
Occupation                     str
Smoking                      int64
Alcohol_Consumption          int64
dtype: object

In [9]:
df.describe()

,ID,Age,Coffee_Intake,Caffeine_mg,Sleep_Hours,BMI,Heart_Rate,Physical_Activity_Hours,Smoking,Alcohol_Consumption
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.00000,10000.000000
mean,5000.50000,34.949100,2.509230,238.411010,6.636220,23.986860,70.617800,7.48704,0.20040,0.300700
std,2886.89568,11.160939,1.450248,137.748815,1.222055,3.906411,9.822951,4.31518,0.40032,0.458585
min,1.00000,18.000000,0.000000,0.000000,3.000000,15.000000,50.000000,0.00000,0.00000,0.000000
25%,2500.75000,26.000000,1.500000,138.750000,5.800000,21.300000,64.000000,3.70000,0.00000,0.000000
50%,5000.50000,34.000000,2.500000,235.400000,6.600000,24.000000,71.000000,7.50000,0.00000,0.000000
75%,7500.25000,43.000000,3.500000,332.025000,7.500000,26.600000,77.000000,11.20000,0.00000,1.000000
max,10000.00000,80.000000,8.200000,780.300000,10.000000,38.200000,109.000000,15.00000,1.00000,1.000000

In [10]:
df.isnull().sum()

ID                            0
Age                           0
Gender                        0
Country                       0
Coffee_Intake                 0
Caffeine_mg                   0
Sleep_Hours                   0
Sleep_Quality                 0
BMI                           0
Heart_Rate                    0
Stress_Level                  0
Physical_Activity_Hours       0
Health_Issues              5941
Occupation                    0
Smoking                       0
Alcohol_Consumption           0
dtype: int64

In [13]:
(df.isnull().sum() / len(df)) * 100

ID                          0.00
Age                         0.00
Gender                      0.00
Country                     0.00
Coffee_Intake               0.00
Caffeine_mg                 0.00
Sleep_Hours                 0.00
Sleep_Quality               0.00
BMI                         0.00
Heart_Rate                  0.00
Stress_Level                0.00
Physical_Activity_Hours     0.00
Health_Issues              59.41
Occupation                  0.00
Smoking                     0.00
Alcohol_Consumption         0.00
dtype: float64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df = df.drop_duplicates()

print('Duplicados eliminados')

Duplicados eliminados

In [16]:
columnas_numericas = df.select_dtypes(include=np.number).columns

columnas_numericas

Index(['ID', 'Age', 'Coffee_Intake', 'Caffeine_mg', 'Sleep_Hours', 'BMI',
       'Heart_Rate', 'Physical_Activity_Hours', 'Smoking',
       'Alcohol_Consumption'],
      dtype='str')

In [17]:
for columna in columnas_numericas:
    moda = df[columna].mode()[0]
    df[columna] = df[columna].fillna(moda)

In [18]:
columna_categorias = df.select_dtypes(include='object').columns

columna_categorias

/tmp/ipykernel_4995/4228879983.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columna_categorias = df.select_dtypes(include='object').columns

Index(['Gender', 'Country', 'Sleep_Quality', 'Stress_Level', 'Health_Issues',
       'Occupation'],
      dtype='str')

In [20]:
for columna in columna_categorias:
    moda = df[columna].mode()[0]
    df[columna] = df[columna].fillna(moda)

print('Valores corregidos')

Valores corregidos

In [21]:
df['Gender'].value_counts()

Gender
Female    5001
Male      4773
Other      226
Name: count, dtype: int64

In [22]:
df['Country'].value_counts()

Country
Canada         543
India          524
Norway         523
China          521
UK             519
Sweden         513
South Korea    512
Finland        510
Italy          509
Switzerland    500
France         499
Germany        497
Belgium        497
Australia      497
Netherlands    494
Spain          486
Mexico         483
Japan          469
Brazil         456
USA            448
Name: count, dtype: int64

In [23]:
df['Stress_Level'].value_counts()

Stress_Level
Low       6989
Medium    2050
High       961
Name: count, dtype: int64

In [24]:
df['Sleep_Quality'].value_counts()

Sleep_Quality
Good         5637
Fair         2050
Excellent    1352
Poor          961
Name: count, dtype: int64

Transformacion de datos

In [ ]:
df['Grupo_edad'] = pd.cut(
    df['Age'],
)